-- MySQL Script generated by MySQL Workbench
-- Вт 12 фев 2019 00:56:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MapOlshanikDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MapOlshanikDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MapOlshanikDB` DEFAULT CHARACTER SET utf8 ;
USE `MapOlshanikDB` ;

-- -----------------------------------------------------
-- Table `MapOlshanikDB`.`Borders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MapOlshanikDB`.`Borders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `point` POINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MapOlshanikDB`.`Polygons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MapOlshanikDB`.`Polygons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MapOlshanikDB`.`BordersPolygons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MapOlshanikDB`.`BordersPolygons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_border` INT NOT NULL,
  `id_polygon` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_BordersPolygons_Borders_idx` (`id_border` ASC),
  INDEX `fk_BordersPolygons_Polygons_idx` (`id_polygon` ASC),
  CONSTRAINT `fk_BordersPolygons_Borders`
    FOREIGN KEY (`id_border`)
    REFERENCES `MapOlshanikDB`.`Borders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BordersPolygons_Polygons`
    FOREIGN KEY (`id_polygon`)
    REFERENCES `MapOlshanikDB`.`Polygons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MapOlshanikDB`.`Coordinates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MapOlshanikDB`.`Coordinates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `point` POINT NOT NULL,
  `height` FLOAT NULL DEFAULT NULL,
  `id_polygon` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Coordinates_Polugons_idx` (`id_polygon` ASC),
  CONSTRAINT `fk_Coordinates_Polugons`
    FOREIGN KEY (`id_polygon`)
    REFERENCES `MapOlshanikDB`.`Polygons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MapOlshanikDB`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MapOlshanikDB`.`Teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `id_polygon` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Teams_Polygons_idx` (`id_polygon` ASC),
  CONSTRAINT `fk_Teams_Polygons`
    FOREIGN KEY (`id_polygon`)
    REFERENCES `MapOlshanikDB`.`Polygons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MapOlshanikDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MapOlshanikDB`.`Users` (
  `id` BIGINT NOT NULL,
  `firstName` NVARCHAR(50) NOT NULL,
  `lastName` NVARCHAR(50) NOT NULL,
  `nickName` NVARCHAR(50) NOT NULL,
  `id_team` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Users_1_idx` (`id_team` ASC),
  CONSTRAINT `fk_Users_Teams`
    FOREIGN KEY (`id_team`)
    REFERENCES `MapOlshanikDB`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
